version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ryan"
    assignees:
      - "ryan"

  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ryan"
    assignees:
      - "ryan"
    groups:
      # Group development dependencies
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "isort"
          - "mypy"
          - "ruff"
          - "bandit"
          - "safety"
          - "coverage"
          - "pytest-cov"
      # Group build dependencies
      build-dependencies:
        patterns:
          - "build"
          - "twine"
          - "setuptools"
          - "wheel"
