name: Documentation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Install documentation tools
      run: |
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

    - name: Check README
      run: |
        echo "Checking README.md..."
        test -f README.md
        test -s README.md
        echo "README.md is valid"

    - name: Check docstrings
      run: |
        pip install docstring-coverage
        docstring-coverage src/pom_reader/ --fail-under=80

    - name: Check for TODO/FIXME comments
      run: |
        echo "Checking for TODO/FIXME comments..."
        grep -r "TODO\|FIXME" src/ || echo "No TODO/FIXME comments found"

    - name: Validate markdown
      run: |
        pip install markdownlint-cli
        markdownlint README.md || echo "Markdown linting completed with warnings"

    - name: Generate API documentation
      run: |
        echo "Generating API documentation..."
        python -c "
        from pom_reader import PomReader, PomAnalyzer
        from pom_reader.models import *
        print('All imports successful')
        "

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: |
          README.md
          *.md
